library(shiny)
library(plotly)
library(finalProject)
library(shinyjs)


shinyUI(fluidPage(title="STAT 585",useShinyjs(),
                  tabsetPanel(#widths=c(2,10),
                    tabPanel(h4("Normal Plot"),
                             sidebarLayout(
                               sidebarPanel(width=3,
                                            selectInput("distributionType",
                                                        label="Population Shape",
                                                        choices = list("Normal",
                                                                       "Another Option"),
                                                        selected="Normal"),
                                            numericInput("normalPlot_mu",
                                                         label = "Population Mean",
                                                         value=0),
                                            numericInput("normalPlot_sigma",
                                                         label = "Population Standard Deviation",
                                                         value=1),
                                            numericInput("alpha",
                                                         label = "Significance Level",
                                                         value=.05),
                                            selectInput("dir",
                                                        label="Direction of Alternative Hypothesis",
                                                        choices = list(intToUtf8("8800"), #8800 is HTML for "not equal to"
                                                                       ">",
                                                                       "<")),
                                            numericInput("obsZ",
                                                         label= "Observed Test Statistic",
                                                         value=0)),
                               # Show a plot of the generated distribution
                               mainPanel(
                                 plotlyOutput(outputId = "distPlot",height="700px")
                               ))),
                    tabPanel(h4("Sampling Distribution of Sample Means"),
                             sidebarLayout(
                               sidebarPanel(width=3,selectInput("distributionType",
                                                                label="Population Shape",
                                                                choices = list("Normal",
                                                                               "Another Option"),
                                                                selected="Normal"),
                                            numericInput("sampleDist_mu",
                                                         label = "Population Mean",
                                                         value=0),
                                            numericInput("sampleDist_sigma",
                                                         label = "Population Standard Deviation",
                                                         value=1),
                                            textInput("name",
                                                      label = "Name of Variable",
                                                      value = "Height"),
                                            numericInput("sampleSize",
                                                         label = "Sample Size",
                                                         value=25),
                                            numericInput("numSamples",
                                                         label = "Number of Samples",
                                                         value=1),
                                            actionButton("drawSample",label = "Draw Additional Samples"),
                                            actionButton("resetMeanSample",label="Reset Samples"),
                                            downloadButton("downloadSampleData","Download Sample Data")),
                               # Show a plot of the generated distribution
                               mainPanel(
                                 fluidRow(
                                   h4("Distribution of Sample Data:"),
                                   column(7,plotlyOutput(outputId = "randomSampleDist",height = "300px")),
                                   h4("Sample Summary Table:"),
                                   column(5,tableOutput("randomSampleTable"))),
                                 h4("Distribution of Sample Means:"),
                                 plotlyOutput(outputId = "meanSamplingDist",height="300px"),
                                 h4("Means Summary Table:"),
                                 tableOutput("meansTable")
                               ))),
                    tabPanel(h4("Hypothesis Test Practice"),
                             fluidRow(
                               br(),
                               column(width=3,
                                      actionButton("newQuestion",label=h4("New Hypothesis Test Problem"))
                               )
                               ,
                               # sidebarLayout(
                               #   sidebarPanel(width=3,
                               #     actionButton("newQuestion",label="New Hypothesis Test Problem")
                               #   ),
                               column(width=9,#withMathJax(),
                                      # br(),
                                      h3("Prompt:"),
                                      h4(textOutput("prompt")),
                                      fluidRow(column(width=9,h3("1) Null Hypothesis:"))),
                                      fluidRow(column(width=1,h4(paste0(intToUtf8("0x03BC")," ="),
                                                                 style="padding: 0px; width: 30px;")),
                                               column(width=2,uiOutput("nullHypVal"),
                                                      style="padding: 0px;"),
                                               column(width=6,textOutput("nullHypFeedback"),
                                                      style="padding: 0px;")),
                                      fluidRow(column(width=9,h3("2) Alternative Hypothesis:"))),
                                      fluidRow(column(width=1,h4(intToUtf8("0x03BC")),
                                                      style="padding: 0px; width: 20px;"),
                                               column(width=1,h4(uiOutput("altHypDir")),
                                                      style="padding: 0px;"),
                                               column(width=2,h4(uiOutput("altHypVal")),
                                                      style="padding: 0px;"),
                                               column(width=5,textOutput("altHypFeedback"),
                                                      style="padding:0px;")),
                                      fluidRow(column(width=9,h3("3) Test Statistic (within .1 of true value):"))),
                                      fluidRow(column(width=1,h4("z ="),
                                                      style="padding: 0px;"),
                                               column(width=2,h4(uiOutput("testStat")),
                                                      style="padding: 0px;"),
                                               column(width=6,textOutput("testStatFeedback"),
                                                      style="padding: 0px;")),
                                      fluidRow(column(width=9,h3("4) Compare Test Statistic to Null Distribution:"))),
                                      fluidRow(column(width=2,h4(uiOutput("testSize"))),
                                               # div(style="display: inline-block;width: 75px;",h4(uiOutput("nullSD"))),
                                               column(width=3,actionButton("plotNull",h4("Plot Null Distribution")),
                                                      style="padding:0px;"),
                                               column(width=4,textOutput("testSizeFeedback"),
                                                      style="padding:0px;")),
                                      plotlyOutput("nullDist",height="300px"),
                                      fluidRow(column(width=9,h3("5) Decision:"))),
                                      fluidRow(column(width=3,h4(uiOutput("decision")),
                                                      style="padding:0px;"),
                                               column(width=6,textOutput("decisionFeedback"),
                                                      style="padding:0px;")),
                                      h3("Problem Source:"),
                                      h4(uiOutput("source"))#,
                                      # fluidRow(column(width=9,h3("6) Conclusion:"))),
                                      # fluidRow(column(width=2,h4("There is ")),
                                      #          column(width=2,h4(uiOutput("conclusionSignif"))),
                                      #          column(width=5,h4(" evidence to conclude that the true mean is ")))
                               ))))))
